#!/usr/bin/env node
/*
 * Bakes the 12 piece glyphs into raw RGBA sprites for the link-preview
 * worker's PNG renderer, using headless Chromium so the pieces match the
 * app's board exactly (same Unicode glyphs, same white-fill/dark-outline
 * styling). Output: worker/sprites.generated.mjs (committed, so deploys
 * never need a browser).
 *
 * Run:  NODE_PATH=$(npm root -g) node worker/bake-sprites.js
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { chromium } = require("playwright");

const CELL = 76; // must match SQUARE in worker.mjs

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const sprites = await page.evaluate((cell) => {
    const GLYPHS = { k: "♚", q: "♛", r: "♜", b: "♝", n: "♞", p: "♟" };
    const out = {};
    const canvas = document.createElement("canvas");
    canvas.width = cell;
    canvas.height = cell;
    const ctx = canvas.getContext("2d", { willReadFrequently: true });
    for (const color of ["w", "b"]) {
      for (const kind of Object.keys(GLYPHS)) {
        ctx.clearRect(0, 0, cell, cell);
        ctx.font = Math.round(cell * 0.88) + 'px "Apple Symbols", "Segoe UI Symbol", "Noto Sans Symbols 2", sans-serif';
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        const glyph = GLYPHS[kind] + "︎";
        const x = cell / 2;
        const y = cell / 2 + cell * 0.04;
        if (color === "w") {
          ctx.lineWidth = Math.max(2, cell * 0.045);
          ctx.lineJoin = "round";
          ctx.strokeStyle = "rgba(0,0,0,0.85)";
          ctx.strokeText(glyph, x, y);
          ctx.fillStyle = "#ffffff";
          ctx.fillText(glyph, x, y);
        } else {
          ctx.lineWidth = Math.max(1.5, cell * 0.03);
          ctx.lineJoin = "round";
          ctx.strokeStyle = "rgba(255,255,255,0.35)";
          ctx.strokeText(glyph, x, y);
          ctx.fillStyle = "#151210";
          ctx.fillText(glyph, x, y);
        }
        const data = ctx.getImageData(0, 0, cell, cell).data;
        let binary = "";
        for (let i = 0; i < data.length; i++) binary += String.fromCharCode(data[i]);
        out[color + kind] = btoa(binary);
      }
    }
    return out;
  }, CELL);
  await browser.close();

  const body =
    "// GENERATED by worker/bake-sprites.js — do not edit by hand.\n" +
    "// Raw RGBA piece sprites, " + CELL + "x" + CELL + ", keyed by color+kind (e.g. \"wk\", \"bp\").\n" +
    "export const SPRITE_SIZE = " + CELL + ";\n" +
    "export const SPRITES = " + JSON.stringify(sprites, null, 0) + ";\n";
  const file = path.join(__dirname, "sprites.generated.mjs");
  fs.writeFileSync(file, body);
  console.log("wrote " + file + " (" + (body.length / 1024).toFixed(0) + " KB)");
})();
